### ISSUE TITLE
Lcd of Nokia 5210 or 5110?

### ISSUE THREAD

**Issue by albertored** [ulfwin/Arduino-Nokia-5210-LCD#1]
The repo title refers to nokia 5210 but comments inside the code refer to nokia 5110, what is the correct phone?

**Comment by ulfwin** [comment]
It is for a 5210. The reason it mentions 5110 is that I used almost everything from Adafruits repository, which is made for 5110.

Please use this repo instead, where I forked the adafruit library:
https://github.com/ulfwin/Adafruit-PCD8544-Nokia-5110-LCD-library

If you want more instructions, you can take a look at my blog post:
http://dontbuyjustmake.blogspot.nl/2015/01/reusing-your-ancient-mobile-phone-lcd.html
